#include <QCheckBox>
#include <QComboBox>
#include <QDoubleSpinBox>
#include <QLineEdit>
#include <QPushButton>
#include <QSpinBox>
#include <QtTest>

#include "ui/settings_dialog.h"

class SettingsDialogTest : public QObject
{
    Q_OBJECT

private Q_SLOTS:
    void loadsConfigIntoWidgets();
    void acceptExportsEditedConfig();
    void controlDependenciesTrackCameraAndAutoSettings();
    void endpointPresetAppliesProviderDefaults();
};

void SettingsDialogTest::loadsConfigIntoWidgets()
{
    AppConfig config;
    config.debugMode = false;
    config.offlineMode = true;
    config.startMinimized = true;
    config.autoStartOnLogin = true;
    config.preferredPosition = QStringLiteral("left");
    config.appearanceAsciiWidth = 72;
    config.appearanceFontSizePx = 10;
    config.fullScreenPause = false;
    config.residentMode = true;
    config.idleThresholdSeconds = 240;
    config.idleJitterMinSeconds = -15;
    config.idleJitterMaxSeconds = 45;
    config.autoDismissSeconds = 18;
    config.cameraEnabled = true;
    config.cameraConsentGranted = true;
    config.cameraIndex = 2;
    config.cameraTargetFps = 12;
    config.eyeTrackingEnabled = false;
    config.periodicScanEnabled = false;
    config.periodicScanIntervalMinutes = 45;
    config.scriptedEntranceEnabled = true;
    config.scriptedTrajectoryPath = QStringLiteral("recorded_paths/custom");
    config.voiceScriptsPath = QStringLiteral("characters/default/scripts.json");
    config.ttsProvider = QStringLiteral("edge");
    config.ttsVoice = QStringLiteral("zh-CN-YunxiNeural");
    config.ttsRate = QStringLiteral("+15%");
    config.audioVolume = 0.55;
    config.audioCacheEnabled = false;
    config.microphoneEnabled = true;
    config.voiceInputMode = QStringLiteral("continuous");
    config.wakeupEnabled = true;
    config.wakeupPhrases = { QStringLiteral("小爱同学"), QStringLiteral("看看屏幕") };
    config.wakeupLanguage = QStringLiteral("zh-CN");
    config.asrProvider = QStringLiteral("zhipu_asr");
    config.asrApiKey = QStringLiteral("asr-key");
    config.asrModel = QStringLiteral("glm-asr-2512");
    config.asrBaseUrl = QStringLiteral("https://open.bigmodel.cn/api/paas/v4/audio/transcriptions");
    config.asrTemperature = 0.2;
    config.asrPrompt = QStringLiteral("voice prompt");
    config.idleInvasion.enabled = false;
    config.idleInvasion.startDelayMs = 120000;
    config.idleInvasion.initialSpawnIntervalMs = 9'000;
    config.idleInvasion.minSpawnIntervalMs = 1'500;
    config.idleInvasion.maxInvaders = 33;
    config.idleInvasion.scale = 0.65;
    config.idleInvasion.cellPadding = 12;
    config.idleInvasion.participatingGifs = { QStringLiteral("state1.gif"), QStringLiteral("state5.gif") };
    config.idleInvasion.retreatStyle = QStringLiteral("ripple");
    config.audioOutputReactive = false;
    config.audioOutputPollIntervalMs = 900;
    config.audioMonitorIgnoreCurrentProcessAudio = false;
    config.audioMonitorPreferMediaSessions = false;
    config.audioMonitorIncludeMasterPeakFallback = true;
    config.llmProvider = QStringLiteral("xai");
    config.llmModel = QStringLiteral("grok-4.1");
    config.llmBaseUrl = QStringLiteral("https://api.x.ai");
    config.llmApiKey = QStringLiteral("secret");
    config.commentarySystemPrompt = QStringLiteral("system prompt");
    config.commentaryUserPrompt = QStringLiteral("user prompt");
    config.commentaryNoImagePrompt = QStringLiteral("no image prompt");
    config.commentaryMaxTokens = 88;
    config.commentaryTemperature = 0.35;
    config.commentaryStreamingEnabled = false;
    config.commentaryOcrFallbackEnabled = true;
    config.commentaryStreamChunkChars = 18;
    config.commentaryMaxResponseChars = 66;
    config.commentaryPreambleText = QStringLiteral("让我先看看。");
    config.screenCommentaryAutoEnabled = true;
    config.screenCommentaryAutoIntervalMinutes = 25;

    const QVector<CharacterManifest> characters = {
        CharacterManifest{ QStringLiteral("default"), QStringLiteral("默认角色"), QStringLiteral("root/default") },
        CharacterManifest{ QStringLiteral("beta"), QStringLiteral("测试助手"), QStringLiteral("root/beta") },
    };
    SettingsDialog dialog(config, characters);

    auto *debugCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("debugModeCheckBox"));
    auto *offlineModeCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("offlineModeCheckBox"));
    auto *startMinimizedCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("startMinimizedCheckBox"));
    auto *autoStartOnLoginCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("autoStartOnLoginCheckBox"));
    auto *activeCharacterComboBox = dialog.findChild<QComboBox *>(QStringLiteral("activeCharacterComboBox"));
    auto *preferredPositionComboBox = dialog.findChild<QComboBox *>(QStringLiteral("preferredPositionComboBox"));
    auto *asciiWidthSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("asciiWidthSpinBox"));
    auto *fontSizeSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("fontSizeSpinBox"));
    auto *fullScreenPauseCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("fullScreenPauseCheckBox"));
    auto *residentModeCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("residentModeCheckBox"));
    auto *idleThresholdSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleThresholdSpinBox"));
    auto *idleJitterMinSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleJitterMinSpinBox"));
    auto *idleJitterMaxSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleJitterMaxSpinBox"));
    auto *autoDismissSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("autoDismissSpinBox"));
    auto *cameraEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("cameraEnabledCheckBox"));
    auto *cameraConsentGrantedCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("cameraConsentGrantedCheckBox"));
    auto *cameraIndexSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("cameraIndexSpinBox"));
    auto *cameraTargetFpsSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("cameraTargetFpsSpinBox"));
    auto *eyeTrackingEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("eyeTrackingEnabledCheckBox"));
    auto *periodicScanEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("periodicScanEnabledCheckBox"));
    auto *periodicScanIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("periodicScanIntervalSpinBox"));
    auto *scriptedEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("scriptedEntranceEnabledCheckBox"));
    auto *trajectoryEdit = dialog.findChild<QLineEdit *>(QStringLiteral("scriptedTrajectoryPathEdit"));
    auto *voiceScriptsEdit = dialog.findChild<QLineEdit *>(QStringLiteral("voiceScriptsPathEdit"));
    auto *ttsProviderComboBox = dialog.findChild<QComboBox *>(QStringLiteral("ttsProviderComboBox"));
    auto *ttsVoiceEdit = dialog.findChild<QLineEdit *>(QStringLiteral("ttsVoiceEdit"));
    auto *ttsRateEdit = dialog.findChild<QLineEdit *>(QStringLiteral("ttsRateEdit"));
    auto *audioVolumeSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("audioVolumeSpinBox"));
    auto *audioCacheEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("audioCacheEnabledCheckBox"));
    auto *microphoneEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("microphoneEnabledCheckBox"));
    auto *voiceInputModeComboBox = dialog.findChild<QComboBox *>(QStringLiteral("voiceInputModeComboBox"));
    auto *wakeupEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("wakeupEnabledCheckBox"));
    auto *wakeupPhrasesEdit = dialog.findChild<QLineEdit *>(QStringLiteral("wakeupPhrasesEdit"));
    auto *wakeupLanguageEdit = dialog.findChild<QLineEdit *>(QStringLiteral("wakeupLanguageEdit"));
    auto *asrProviderComboBox = dialog.findChild<QComboBox *>(QStringLiteral("asrProviderComboBox"));
    auto *asrApiKeyEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrApiKeyEdit"));
    auto *asrModelEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrModelEdit"));
    auto *asrBaseUrlEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrBaseUrlEdit"));
    auto *asrTemperatureSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("asrTemperatureSpinBox"));
    auto *asrPromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrPromptEdit"));
    auto *idleInvasionEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("idleInvasionEnabledCheckBox"));
    auto *idleInvasionStartDelaySpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionStartDelaySpinBox"));
    auto *idleInvasionInitialIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionInitialIntervalSpinBox"));
    auto *idleInvasionMinIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionMinIntervalSpinBox"));
    auto *idleInvasionMaxInvadersSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionMaxInvadersSpinBox"));
    auto *idleInvasionScaleSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("idleInvasionScaleSpinBox"));
    auto *idleInvasionCellPaddingSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionCellPaddingSpinBox"));
    auto *idleInvasionGifsEdit = dialog.findChild<QLineEdit *>(QStringLiteral("idleInvasionGifsEdit"));
    auto *idleInvasionRetreatStyleComboBox = dialog.findChild<QComboBox *>(QStringLiteral("idleInvasionRetreatStyleComboBox"));
    auto *reactiveCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("audioOutputReactiveCheckBox"));
    auto *pollSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("audioOutputPollIntervalSpinBox"));
    auto *ignoreCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("ignoreCurrentProcessCheckBox"));
    auto *preferCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("preferMediaSessionsCheckBox"));
    auto *fallbackCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("includeMasterPeakFallbackCheckBox"));
    auto *endpointPresetComboBox = dialog.findChild<QComboBox *>(QStringLiteral("endpointPresetComboBox"));
    auto *providerComboBox = dialog.findChild<QComboBox *>(QStringLiteral("providerComboBox"));
    auto *modelEdit = dialog.findChild<QLineEdit *>(QStringLiteral("modelEdit"));
    auto *baseUrlEdit = dialog.findChild<QLineEdit *>(QStringLiteral("baseUrlEdit"));
    auto *testApiButton = dialog.findChild<QPushButton *>(QStringLiteral("testApiButton"));
    auto *systemPromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentarySystemPromptEdit"));
    auto *userPromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentaryUserPromptEdit"));
    auto *noImagePromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentaryNoImagePromptEdit"));
    auto *maxTokensSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("commentaryMaxTokensSpinBox"));
    auto *temperatureSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("commentaryTemperatureSpinBox"));
    auto *streamingCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("commentaryStreamingEnabledCheckBox"));
    auto *ocrFallbackCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("commentaryOcrFallbackEnabledCheckBox"));
    auto *streamChunkSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("commentaryStreamChunkCharsSpinBox"));
    auto *maxResponseCharsSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("commentaryMaxResponseCharsSpinBox"));
    auto *preambleTextEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentaryPreambleTextEdit"));
    auto *autoCommentaryCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("screenCommentaryAutoEnabledCheckBox"));
    auto *autoCommentaryIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("screenCommentaryAutoIntervalSpinBox"));

    QVERIFY(debugCheckBox != nullptr);
    QVERIFY(offlineModeCheckBox != nullptr);
    QVERIFY(startMinimizedCheckBox != nullptr);
    QVERIFY(autoStartOnLoginCheckBox != nullptr);
    QVERIFY(activeCharacterComboBox != nullptr);
    QVERIFY(preferredPositionComboBox != nullptr);
    QVERIFY(asciiWidthSpinBox != nullptr);
    QVERIFY(fontSizeSpinBox != nullptr);
    QVERIFY(fullScreenPauseCheckBox != nullptr);
    QVERIFY(residentModeCheckBox != nullptr);
    QVERIFY(idleThresholdSpinBox != nullptr);
    QVERIFY(idleJitterMinSpinBox != nullptr);
    QVERIFY(idleJitterMaxSpinBox != nullptr);
    QVERIFY(autoDismissSpinBox != nullptr);
    QVERIFY(cameraEnabledCheckBox != nullptr);
    QVERIFY(cameraConsentGrantedCheckBox != nullptr);
    QVERIFY(cameraIndexSpinBox != nullptr);
    QVERIFY(cameraTargetFpsSpinBox != nullptr);
    QVERIFY(eyeTrackingEnabledCheckBox != nullptr);
    QVERIFY(periodicScanEnabledCheckBox != nullptr);
    QVERIFY(periodicScanIntervalSpinBox != nullptr);
    QVERIFY(scriptedEnabledCheckBox != nullptr);
    QVERIFY(trajectoryEdit != nullptr);
    QVERIFY(voiceScriptsEdit != nullptr);
    QVERIFY(ttsProviderComboBox != nullptr);
    QVERIFY(ttsVoiceEdit != nullptr);
    QVERIFY(ttsRateEdit != nullptr);
    QVERIFY(audioVolumeSpinBox != nullptr);
    QVERIFY(audioCacheEnabledCheckBox != nullptr);
    QVERIFY(microphoneEnabledCheckBox != nullptr);
    QVERIFY(voiceInputModeComboBox != nullptr);
    QVERIFY(wakeupEnabledCheckBox != nullptr);
    QVERIFY(wakeupPhrasesEdit != nullptr);
    QVERIFY(wakeupLanguageEdit != nullptr);
    QVERIFY(asrProviderComboBox != nullptr);
    QVERIFY(asrApiKeyEdit != nullptr);
    QVERIFY(asrModelEdit != nullptr);
    QVERIFY(asrBaseUrlEdit != nullptr);
    QVERIFY(asrTemperatureSpinBox != nullptr);
    QVERIFY(asrPromptEdit != nullptr);
    QVERIFY(microphoneEnabledCheckBox != nullptr);
    QVERIFY(voiceInputModeComboBox != nullptr);
    QVERIFY(wakeupEnabledCheckBox != nullptr);
    QVERIFY(wakeupPhrasesEdit != nullptr);
    QVERIFY(wakeupLanguageEdit != nullptr);
    QVERIFY(asrProviderComboBox != nullptr);
    QVERIFY(asrApiKeyEdit != nullptr);
    QVERIFY(asrModelEdit != nullptr);
    QVERIFY(asrBaseUrlEdit != nullptr);
    QVERIFY(asrTemperatureSpinBox != nullptr);
    QVERIFY(asrPromptEdit != nullptr);
    QVERIFY(idleInvasionEnabledCheckBox != nullptr);
    QVERIFY(idleInvasionStartDelaySpinBox != nullptr);
    QVERIFY(idleInvasionInitialIntervalSpinBox != nullptr);
    QVERIFY(idleInvasionMinIntervalSpinBox != nullptr);
    QVERIFY(idleInvasionMaxInvadersSpinBox != nullptr);
    QVERIFY(idleInvasionScaleSpinBox != nullptr);
    QVERIFY(idleInvasionCellPaddingSpinBox != nullptr);
    QVERIFY(idleInvasionGifsEdit != nullptr);
    QVERIFY(idleInvasionRetreatStyleComboBox != nullptr);
    QVERIFY(reactiveCheckBox != nullptr);
    QVERIFY(pollSpinBox != nullptr);
    QVERIFY(ignoreCheckBox != nullptr);
    QVERIFY(preferCheckBox != nullptr);
    QVERIFY(fallbackCheckBox != nullptr);
    QVERIFY(endpointPresetComboBox != nullptr);
    QVERIFY(providerComboBox != nullptr);
    QVERIFY(modelEdit != nullptr);
    QVERIFY(baseUrlEdit != nullptr);
    QVERIFY(testApiButton != nullptr);
    QVERIFY(systemPromptEdit != nullptr);
    QVERIFY(userPromptEdit != nullptr);
    QVERIFY(noImagePromptEdit != nullptr);
    QVERIFY(maxTokensSpinBox != nullptr);
    QVERIFY(temperatureSpinBox != nullptr);
    QVERIFY(streamingCheckBox != nullptr);
    QVERIFY(ocrFallbackCheckBox != nullptr);
    QVERIFY(streamChunkSpinBox != nullptr);
    QVERIFY(maxResponseCharsSpinBox != nullptr);
    QVERIFY(preambleTextEdit != nullptr);
    QVERIFY(autoCommentaryCheckBox != nullptr);
    QVERIFY(autoCommentaryIntervalSpinBox != nullptr);

    QCOMPARE(debugCheckBox->isChecked(), false);
    QCOMPARE(offlineModeCheckBox->isChecked(), true);
    QCOMPARE(startMinimizedCheckBox->isChecked(), true);
    QCOMPARE(autoStartOnLoginCheckBox->isChecked(), true);
    QCOMPARE(activeCharacterComboBox->currentData().toString(), QStringLiteral("default"));
    QCOMPARE(preferredPositionComboBox->currentData().toString(), QStringLiteral("left"));
    QCOMPARE(asciiWidthSpinBox->value(), 72);
    QCOMPARE(fontSizeSpinBox->value(), 10);
    QCOMPARE(fullScreenPauseCheckBox->isChecked(), false);
    QCOMPARE(residentModeCheckBox->isChecked(), true);
    QCOMPARE(idleThresholdSpinBox->value(), 240);
    QCOMPARE(idleJitterMinSpinBox->value(), -15);
    QCOMPARE(idleJitterMaxSpinBox->value(), 45);
    QCOMPARE(autoDismissSpinBox->value(), 18);
    QCOMPARE(cameraEnabledCheckBox->isChecked(), true);
    QCOMPARE(cameraConsentGrantedCheckBox->isChecked(), true);
    QCOMPARE(cameraIndexSpinBox->value(), 2);
    QCOMPARE(cameraTargetFpsSpinBox->value(), 12);
    QCOMPARE(eyeTrackingEnabledCheckBox->isChecked(), false);
    QCOMPARE(periodicScanEnabledCheckBox->isChecked(), false);
    QCOMPARE(periodicScanIntervalSpinBox->value(), 45);
    QCOMPARE(scriptedEnabledCheckBox->isChecked(), true);
    QCOMPARE(trajectoryEdit->text(), config.scriptedTrajectoryPath);
    QCOMPARE(voiceScriptsEdit->text(), config.voiceScriptsPath);
    QCOMPARE(ttsProviderComboBox->currentData().toString(), QStringLiteral("edge"));
    QCOMPARE(ttsVoiceEdit->text(), config.ttsVoice);
    QCOMPARE(ttsRateEdit->text(), config.ttsRate);
    QCOMPARE(audioVolumeSpinBox->value(), 0.55);
    QCOMPARE(audioCacheEnabledCheckBox->isChecked(), false);
    QCOMPARE(microphoneEnabledCheckBox->isChecked(), true);
    QCOMPARE(voiceInputModeComboBox->currentData().toString(), QStringLiteral("continuous"));
    QCOMPARE(wakeupEnabledCheckBox->isChecked(), true);
    QCOMPARE(wakeupPhrasesEdit->text(), QStringLiteral("小爱同学, 看看屏幕"));
    QCOMPARE(wakeupLanguageEdit->text(), QStringLiteral("zh-CN"));
    QCOMPARE(asrProviderComboBox->currentData().toString(), QStringLiteral("zhipu_asr"));
    QCOMPARE(asrApiKeyEdit->text(), QStringLiteral("asr-key"));
    QCOMPARE(asrModelEdit->text(), QStringLiteral("glm-asr-2512"));
    QCOMPARE(asrBaseUrlEdit->text(), QStringLiteral("https://open.bigmodel.cn/api/paas/v4/audio/transcriptions"));
    QCOMPARE(asrTemperatureSpinBox->value(), 0.2);
    QCOMPARE(asrPromptEdit->text(), QStringLiteral("voice prompt"));
    QCOMPARE(idleInvasionEnabledCheckBox->isChecked(), false);
    QCOMPARE(idleInvasionStartDelaySpinBox->value(), 120);
    QCOMPARE(idleInvasionInitialIntervalSpinBox->value(), 9);
    QCOMPARE(idleInvasionMinIntervalSpinBox->value(), 1);
    QCOMPARE(idleInvasionMaxInvadersSpinBox->value(), 33);
    QCOMPARE(idleInvasionScaleSpinBox->value(), 0.65);
    QCOMPARE(idleInvasionCellPaddingSpinBox->value(), 12);
    QCOMPARE(idleInvasionGifsEdit->text(), QStringLiteral("state1.gif, state5.gif"));
    QCOMPARE(idleInvasionRetreatStyleComboBox->currentData().toString(), QStringLiteral("ripple"));
    QCOMPARE(reactiveCheckBox->isChecked(), false);
    QCOMPARE(pollSpinBox->value(), 900);
    QCOMPARE(ignoreCheckBox->isChecked(), false);
    QCOMPARE(preferCheckBox->isChecked(), false);
    QCOMPARE(fallbackCheckBox->isChecked(), true);
    QCOMPARE(providerComboBox->currentText(), QStringLiteral("xai"));
    QCOMPARE(modelEdit->text(), QStringLiteral("grok-4.1"));
    QCOMPARE(baseUrlEdit->text(), QStringLiteral("https://api.x.ai"));
    QCOMPARE(systemPromptEdit->text(), QStringLiteral("system prompt"));
    QCOMPARE(userPromptEdit->text(), QStringLiteral("user prompt"));
    QCOMPARE(noImagePromptEdit->text(), QStringLiteral("no image prompt"));
    QCOMPARE(maxTokensSpinBox->value(), 88);
    QCOMPARE(temperatureSpinBox->value(), 0.35);
    QCOMPARE(streamingCheckBox->isChecked(), false);
    QCOMPARE(ocrFallbackCheckBox->isChecked(), true);
    QCOMPARE(streamChunkSpinBox->value(), 18);
    QCOMPARE(maxResponseCharsSpinBox->value(), 66);
    QCOMPARE(preambleTextEdit->text(), QStringLiteral("让我先看看。"));
    QCOMPARE(autoCommentaryCheckBox->isChecked(), true);
    QCOMPARE(autoCommentaryIntervalSpinBox->value(), 25);
}

void SettingsDialogTest::acceptExportsEditedConfig()
{
    AppConfig config;
    const QVector<CharacterManifest> characters = {
        CharacterManifest{ QStringLiteral("default"), QStringLiteral("默认角色"), QStringLiteral("root/default") },
        CharacterManifest{ QStringLiteral("beta"), QStringLiteral("测试助手"), QStringLiteral("root/beta") },
    };
    SettingsDialog dialog(config, characters);

    auto *debugCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("debugModeCheckBox"));
    auto *offlineModeCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("offlineModeCheckBox"));
    auto *startMinimizedCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("startMinimizedCheckBox"));
    auto *autoStartOnLoginCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("autoStartOnLoginCheckBox"));
    auto *activeCharacterComboBox = dialog.findChild<QComboBox *>(QStringLiteral("activeCharacterComboBox"));
    auto *preferredPositionComboBox = dialog.findChild<QComboBox *>(QStringLiteral("preferredPositionComboBox"));
    auto *asciiWidthSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("asciiWidthSpinBox"));
    auto *fontSizeSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("fontSizeSpinBox"));
    auto *fullScreenPauseCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("fullScreenPauseCheckBox"));
    auto *residentModeCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("residentModeCheckBox"));
    auto *idleThresholdSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleThresholdSpinBox"));
    auto *idleJitterMinSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleJitterMinSpinBox"));
    auto *idleJitterMaxSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleJitterMaxSpinBox"));
    auto *autoDismissSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("autoDismissSpinBox"));
    auto *cameraEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("cameraEnabledCheckBox"));
    auto *cameraConsentGrantedCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("cameraConsentGrantedCheckBox"));
    auto *cameraIndexSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("cameraIndexSpinBox"));
    auto *cameraTargetFpsSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("cameraTargetFpsSpinBox"));
    auto *eyeTrackingEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("eyeTrackingEnabledCheckBox"));
    auto *periodicScanEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("periodicScanEnabledCheckBox"));
    auto *periodicScanIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("periodicScanIntervalSpinBox"));
    auto *scriptedEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("scriptedEntranceEnabledCheckBox"));
    auto *trajectoryEdit = dialog.findChild<QLineEdit *>(QStringLiteral("scriptedTrajectoryPathEdit"));
    auto *voiceScriptsEdit = dialog.findChild<QLineEdit *>(QStringLiteral("voiceScriptsPathEdit"));
    auto *ttsProviderComboBox = dialog.findChild<QComboBox *>(QStringLiteral("ttsProviderComboBox"));
    auto *ttsVoiceEdit = dialog.findChild<QLineEdit *>(QStringLiteral("ttsVoiceEdit"));
    auto *ttsRateEdit = dialog.findChild<QLineEdit *>(QStringLiteral("ttsRateEdit"));
    auto *audioVolumeSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("audioVolumeSpinBox"));
    auto *audioCacheEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("audioCacheEnabledCheckBox"));
    auto *microphoneEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("microphoneEnabledCheckBox"));
    auto *voiceInputModeComboBox = dialog.findChild<QComboBox *>(QStringLiteral("voiceInputModeComboBox"));
    auto *wakeupEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("wakeupEnabledCheckBox"));
    auto *wakeupPhrasesEdit = dialog.findChild<QLineEdit *>(QStringLiteral("wakeupPhrasesEdit"));
    auto *wakeupLanguageEdit = dialog.findChild<QLineEdit *>(QStringLiteral("wakeupLanguageEdit"));
    auto *asrProviderComboBox = dialog.findChild<QComboBox *>(QStringLiteral("asrProviderComboBox"));
    auto *asrApiKeyEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrApiKeyEdit"));
    auto *asrModelEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrModelEdit"));
    auto *asrBaseUrlEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrBaseUrlEdit"));
    auto *asrTemperatureSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("asrTemperatureSpinBox"));
    auto *asrPromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("asrPromptEdit"));
    auto *idleInvasionEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("idleInvasionEnabledCheckBox"));
    auto *idleInvasionStartDelaySpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionStartDelaySpinBox"));
    auto *idleInvasionInitialIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionInitialIntervalSpinBox"));
    auto *idleInvasionMinIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionMinIntervalSpinBox"));
    auto *idleInvasionMaxInvadersSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionMaxInvadersSpinBox"));
    auto *idleInvasionScaleSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("idleInvasionScaleSpinBox"));
    auto *idleInvasionCellPaddingSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("idleInvasionCellPaddingSpinBox"));
    auto *idleInvasionGifsEdit = dialog.findChild<QLineEdit *>(QStringLiteral("idleInvasionGifsEdit"));
    auto *idleInvasionRetreatStyleComboBox = dialog.findChild<QComboBox *>(QStringLiteral("idleInvasionRetreatStyleComboBox"));
    auto *reactiveCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("audioOutputReactiveCheckBox"));
    auto *pollSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("audioOutputPollIntervalSpinBox"));
    auto *ignoreCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("ignoreCurrentProcessCheckBox"));
    auto *preferCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("preferMediaSessionsCheckBox"));
    auto *fallbackCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("includeMasterPeakFallbackCheckBox"));
    auto *endpointPresetComboBox = dialog.findChild<QComboBox *>(QStringLiteral("endpointPresetComboBox"));
    auto *providerComboBox = dialog.findChild<QComboBox *>(QStringLiteral("providerComboBox"));
    auto *modelEdit = dialog.findChild<QLineEdit *>(QStringLiteral("modelEdit"));
    auto *baseUrlEdit = dialog.findChild<QLineEdit *>(QStringLiteral("baseUrlEdit"));
    auto *apiKeyEdit = dialog.findChild<QLineEdit *>(QStringLiteral("apiKeyEdit"));
    auto *testApiButton = dialog.findChild<QPushButton *>(QStringLiteral("testApiButton"));
    auto *systemPromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentarySystemPromptEdit"));
    auto *userPromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentaryUserPromptEdit"));
    auto *noImagePromptEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentaryNoImagePromptEdit"));
    auto *maxTokensSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("commentaryMaxTokensSpinBox"));
    auto *temperatureSpinBox = dialog.findChild<QDoubleSpinBox *>(QStringLiteral("commentaryTemperatureSpinBox"));
    auto *streamingCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("commentaryStreamingEnabledCheckBox"));
    auto *ocrFallbackCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("commentaryOcrFallbackEnabledCheckBox"));
    auto *streamChunkSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("commentaryStreamChunkCharsSpinBox"));
    auto *maxResponseCharsSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("commentaryMaxResponseCharsSpinBox"));
    auto *preambleTextEdit = dialog.findChild<QLineEdit *>(QStringLiteral("commentaryPreambleTextEdit"));
    auto *autoCommentaryCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("screenCommentaryAutoEnabledCheckBox"));
    auto *autoCommentaryIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("screenCommentaryAutoIntervalSpinBox"));

    QVERIFY(debugCheckBox != nullptr);
    QVERIFY(offlineModeCheckBox != nullptr);
    QVERIFY(startMinimizedCheckBox != nullptr);
    QVERIFY(autoStartOnLoginCheckBox != nullptr);
    QVERIFY(activeCharacterComboBox != nullptr);
    QVERIFY(preferredPositionComboBox != nullptr);
    QVERIFY(asciiWidthSpinBox != nullptr);
    QVERIFY(fontSizeSpinBox != nullptr);
    QVERIFY(fullScreenPauseCheckBox != nullptr);
    QVERIFY(residentModeCheckBox != nullptr);
    QVERIFY(idleThresholdSpinBox != nullptr);
    QVERIFY(idleJitterMinSpinBox != nullptr);
    QVERIFY(idleJitterMaxSpinBox != nullptr);
    QVERIFY(autoDismissSpinBox != nullptr);
    QVERIFY(cameraEnabledCheckBox != nullptr);
    QVERIFY(cameraConsentGrantedCheckBox != nullptr);
    QVERIFY(cameraIndexSpinBox != nullptr);
    QVERIFY(cameraTargetFpsSpinBox != nullptr);
    QVERIFY(eyeTrackingEnabledCheckBox != nullptr);
    QVERIFY(periodicScanEnabledCheckBox != nullptr);
    QVERIFY(periodicScanIntervalSpinBox != nullptr);
    QVERIFY(scriptedEnabledCheckBox != nullptr);
    QVERIFY(trajectoryEdit != nullptr);
    QVERIFY(voiceScriptsEdit != nullptr);
    QVERIFY(ttsProviderComboBox != nullptr);
    QVERIFY(ttsVoiceEdit != nullptr);
    QVERIFY(ttsRateEdit != nullptr);
    QVERIFY(audioVolumeSpinBox != nullptr);
    QVERIFY(audioCacheEnabledCheckBox != nullptr);
    QVERIFY(microphoneEnabledCheckBox != nullptr);
    QVERIFY(voiceInputModeComboBox != nullptr);
    QVERIFY(wakeupEnabledCheckBox != nullptr);
    QVERIFY(wakeupPhrasesEdit != nullptr);
    QVERIFY(wakeupLanguageEdit != nullptr);
    QVERIFY(asrProviderComboBox != nullptr);
    QVERIFY(asrApiKeyEdit != nullptr);
    QVERIFY(asrModelEdit != nullptr);
    QVERIFY(asrBaseUrlEdit != nullptr);
    QVERIFY(asrTemperatureSpinBox != nullptr);
    QVERIFY(asrPromptEdit != nullptr);
    QVERIFY(idleInvasionEnabledCheckBox != nullptr);
    QVERIFY(idleInvasionStartDelaySpinBox != nullptr);
    QVERIFY(idleInvasionInitialIntervalSpinBox != nullptr);
    QVERIFY(idleInvasionMinIntervalSpinBox != nullptr);
    QVERIFY(idleInvasionMaxInvadersSpinBox != nullptr);
    QVERIFY(idleInvasionScaleSpinBox != nullptr);
    QVERIFY(idleInvasionCellPaddingSpinBox != nullptr);
    QVERIFY(idleInvasionGifsEdit != nullptr);
    QVERIFY(idleInvasionRetreatStyleComboBox != nullptr);
    QVERIFY(reactiveCheckBox != nullptr);
    QVERIFY(pollSpinBox != nullptr);
    QVERIFY(ignoreCheckBox != nullptr);
    QVERIFY(preferCheckBox != nullptr);
    QVERIFY(fallbackCheckBox != nullptr);
    QVERIFY(endpointPresetComboBox != nullptr);
    QVERIFY(providerComboBox != nullptr);
    QVERIFY(modelEdit != nullptr);
    QVERIFY(baseUrlEdit != nullptr);
    QVERIFY(apiKeyEdit != nullptr);
    QVERIFY(testApiButton != nullptr);
    QVERIFY(systemPromptEdit != nullptr);
    QVERIFY(userPromptEdit != nullptr);
    QVERIFY(noImagePromptEdit != nullptr);
    QVERIFY(maxTokensSpinBox != nullptr);
    QVERIFY(temperatureSpinBox != nullptr);
    QVERIFY(streamingCheckBox != nullptr);
    QVERIFY(ocrFallbackCheckBox != nullptr);
    QVERIFY(streamChunkSpinBox != nullptr);
    QVERIFY(maxResponseCharsSpinBox != nullptr);
    QVERIFY(preambleTextEdit != nullptr);
    QVERIFY(autoCommentaryCheckBox != nullptr);
    QVERIFY(autoCommentaryIntervalSpinBox != nullptr);

    debugCheckBox->setChecked(false);
    offlineModeCheckBox->setChecked(true);
    startMinimizedCheckBox->setChecked(true);
    autoStartOnLoginCheckBox->setChecked(true);
    activeCharacterComboBox->setCurrentIndex(qMax(0, activeCharacterComboBox->findData(QStringLiteral("beta"))));
    preferredPositionComboBox->setCurrentIndex(qMax(0, preferredPositionComboBox->findData(QStringLiteral("left"))));
    asciiWidthSpinBox->setValue(84);
    fontSizeSpinBox->setValue(12);
    fullScreenPauseCheckBox->setChecked(false);
    residentModeCheckBox->setChecked(true);
    idleThresholdSpinBox->setValue(240);
    idleJitterMinSpinBox->setValue(-20);
    idleJitterMaxSpinBox->setValue(40);
    autoDismissSpinBox->setValue(18);
    cameraEnabledCheckBox->setChecked(true);
    cameraConsentGrantedCheckBox->setChecked(true);
    cameraIndexSpinBox->setValue(3);
    cameraTargetFpsSpinBox->setValue(10);
    eyeTrackingEnabledCheckBox->setChecked(false);
    periodicScanEnabledCheckBox->setChecked(false);
    periodicScanIntervalSpinBox->setValue(45);
    scriptedEnabledCheckBox->setChecked(true);
    trajectoryEdit->setText(QStringLiteral("recorded_paths/alt"));
    voiceScriptsEdit->setText(QStringLiteral("characters/default/scripts.json"));
    ttsProviderComboBox->setCurrentIndex(qMax(0, ttsProviderComboBox->findData(QStringLiteral("edge"))));
    ttsVoiceEdit->setText(QStringLiteral("zh-CN-YunxiNeural"));
    ttsRateEdit->setText(QStringLiteral("+15%"));
    audioVolumeSpinBox->setValue(0.55);
    audioCacheEnabledCheckBox->setChecked(false);
    microphoneEnabledCheckBox->setChecked(true);
    voiceInputModeComboBox->setCurrentIndex(qMax(0, voiceInputModeComboBox->findData(QStringLiteral("continuous"))));
    wakeupEnabledCheckBox->setChecked(true);
    wakeupPhrasesEdit->setText(QStringLiteral("小爱同学, 看看屏幕"));
    wakeupLanguageEdit->setText(QStringLiteral("zh-CN"));
    asrProviderComboBox->setCurrentIndex(qMax(0, asrProviderComboBox->findData(QStringLiteral("openai_whisper"))));
    asrApiKeyEdit->setText(QStringLiteral("asr-secret"));
    asrModelEdit->setText(QStringLiteral("whisper-1"));
    asrBaseUrlEdit->setText(QStringLiteral("https://api.openai.com/v1/"));
    asrTemperatureSpinBox->setValue(0.3);
    asrPromptEdit->setText(QStringLiteral("voice prompt"));
    idleInvasionEnabledCheckBox->setChecked(false);
    idleInvasionStartDelaySpinBox->setValue(120);
    idleInvasionInitialIntervalSpinBox->setValue(9);
    idleInvasionMinIntervalSpinBox->setValue(2);
    idleInvasionMaxInvadersSpinBox->setValue(33);
    idleInvasionScaleSpinBox->setValue(0.65);
    idleInvasionCellPaddingSpinBox->setValue(12);
    idleInvasionGifsEdit->setText(QStringLiteral("state1.gif, state5.gif"));
    idleInvasionRetreatStyleComboBox->setCurrentIndex(idleInvasionRetreatStyleComboBox->findData(QStringLiteral("ripple")));
    reactiveCheckBox->setChecked(false);
    pollSpinBox->setValue(1200);
    ignoreCheckBox->setChecked(false);
    preferCheckBox->setChecked(false);
    fallbackCheckBox->setChecked(true);
    providerComboBox->setCurrentText(QStringLiteral("deepseek"));
    modelEdit->setText(QStringLiteral("deepseek-chat"));
    baseUrlEdit->setText(QStringLiteral("https://api.deepseek.com/v1/"));
    apiKeyEdit->setText(QStringLiteral("edited-key"));
    systemPromptEdit->setText(QStringLiteral("edited system"));
    userPromptEdit->setText(QStringLiteral("edited user"));
    noImagePromptEdit->setText(QStringLiteral("edited no image"));
    maxTokensSpinBox->setValue(92);
    temperatureSpinBox->setValue(0.55);
    streamingCheckBox->setChecked(true);
    ocrFallbackCheckBox->setChecked(true);
    streamChunkSpinBox->setValue(24);
    maxResponseCharsSpinBox->setValue(96);
    preambleTextEdit->setText(QStringLiteral("编辑后的前导语"));
    autoCommentaryCheckBox->setChecked(true);
    autoCommentaryIntervalSpinBox->setValue(19);

    dialog.accept();
    const AppConfig edited = dialog.editedConfig();

    QCOMPARE(edited.debugMode, false);
    QCOMPARE(edited.offlineMode, true);
    QCOMPARE(edited.startMinimized, true);
    QCOMPARE(edited.autoStartOnLogin, true);
    QCOMPARE(edited.activeCharacterId, QStringLiteral("beta"));
    QCOMPARE(edited.preferredPosition, QStringLiteral("left"));
    QCOMPARE(edited.appearanceAsciiWidth, 84);
    QCOMPARE(edited.appearanceFontSizePx, 12);
    QCOMPARE(edited.fullScreenPause, false);
    QCOMPARE(edited.residentMode, true);
    QCOMPARE(edited.idleThresholdSeconds, 240);
    QCOMPARE(edited.idleJitterMinSeconds, -20);
    QCOMPARE(edited.idleJitterMaxSeconds, 40);
    QCOMPARE(edited.autoDismissSeconds, 18);
    QCOMPARE(edited.cameraEnabled, true);
    QCOMPARE(edited.cameraConsentGranted, true);
    QCOMPARE(edited.cameraIndex, 3);
    QCOMPARE(edited.cameraTargetFps, 10);
    QCOMPARE(edited.eyeTrackingEnabled, false);
    QCOMPARE(edited.periodicScanEnabled, false);
    QCOMPARE(edited.periodicScanIntervalMinutes, 45);
    QCOMPARE(edited.scriptedEntranceEnabled, true);
    QCOMPARE(edited.scriptedTrajectoryPath, QStringLiteral("recorded_paths/alt"));
    QCOMPARE(edited.voiceScriptsPath, QStringLiteral("characters/default/scripts.json"));
    QCOMPARE(edited.ttsProvider, QStringLiteral("edge"));
    QCOMPARE(edited.ttsVoice, QStringLiteral("zh-CN-YunxiNeural"));
    QCOMPARE(edited.ttsRate, QStringLiteral("+15%"));
    QCOMPARE(edited.audioVolume, 0.55);
    QCOMPARE(edited.audioCacheEnabled, false);
    QCOMPARE(edited.microphoneEnabled, true);
    QCOMPARE(edited.voiceInputMode, QStringLiteral("continuous"));
    QCOMPARE(edited.wakeupEnabled, true);
    QCOMPARE(edited.wakeupPhrases, QStringList({ QStringLiteral("小爱同学"), QStringLiteral("看看屏幕") }));
    QCOMPARE(edited.wakeupLanguage, QStringLiteral("zh-CN"));
    QCOMPARE(edited.asrProvider, QStringLiteral("openai_whisper"));
    QCOMPARE(edited.asrApiKey, QStringLiteral("asr-secret"));
    QCOMPARE(edited.asrModel, QStringLiteral("whisper-1"));
    QCOMPARE(edited.asrBaseUrl, QStringLiteral("https://api.openai.com/v1"));
    QCOMPARE(edited.asrTemperature, 0.3);
    QCOMPARE(edited.asrPrompt, QStringLiteral("voice prompt"));
    QCOMPARE(edited.idleInvasion.enabled, false);
    QCOMPARE(edited.idleInvasion.startDelayMs, 120000);
    QCOMPARE(edited.idleInvasion.initialSpawnIntervalMs, 9000);
    QCOMPARE(edited.idleInvasion.minSpawnIntervalMs, 2000);
    QCOMPARE(edited.idleInvasion.maxInvaders, 33);
    QCOMPARE(edited.idleInvasion.scale, 0.65);
    QCOMPARE(edited.idleInvasion.cellPadding, 12);
    QCOMPARE(edited.idleInvasion.participatingGifs, QStringList({ QStringLiteral("state1.gif"), QStringLiteral("state5.gif") }));
    QCOMPARE(edited.idleInvasion.retreatStyle, QStringLiteral("ripple"));
    QCOMPARE(edited.audioOutputReactive, false);
    QCOMPARE(edited.audioOutputPollIntervalMs, 1200);
    QCOMPARE(edited.audioMonitorIgnoreCurrentProcessAudio, false);
    QCOMPARE(edited.audioMonitorPreferMediaSessions, false);
    QCOMPARE(edited.audioMonitorIncludeMasterPeakFallback, true);
    QCOMPARE(edited.llmProvider, QStringLiteral("deepseek"));
    QCOMPARE(edited.llmModel, QStringLiteral("deepseek-chat"));
    QCOMPARE(edited.llmBaseUrl, QStringLiteral("https://api.deepseek.com/v1"));
    QCOMPARE(edited.llmApiKey, QStringLiteral("edited-key"));
    QCOMPARE(edited.commentarySystemPrompt, QStringLiteral("edited system"));
    QCOMPARE(edited.commentaryUserPrompt, QStringLiteral("edited user"));
    QCOMPARE(edited.commentaryNoImagePrompt, QStringLiteral("edited no image"));
    QCOMPARE(edited.commentaryMaxTokens, 92);
    QCOMPARE(edited.commentaryTemperature, 0.55);
    QCOMPARE(edited.commentaryStreamingEnabled, true);
    QCOMPARE(edited.commentaryOcrFallbackEnabled, true);
    QCOMPARE(edited.commentaryStreamChunkChars, 24);
    QCOMPARE(edited.commentaryMaxResponseChars, 96);
    QCOMPARE(edited.commentaryPreambleText, QStringLiteral("编辑后的前导语"));
    QCOMPARE(edited.screenCommentaryAutoEnabled, true);
    QCOMPARE(edited.screenCommentaryAutoIntervalMinutes, 19);
}

void SettingsDialogTest::controlDependenciesTrackCameraAndAutoSettings()
{
    AppConfig config;
    config.offlineMode = false;
    config.cameraEnabled = false;
    config.cameraConsentGranted = false;
    config.periodicScanEnabled = true;
    config.microphoneEnabled = false;
    config.voiceInputMode = QStringLiteral("push_to_talk");
    config.wakeupEnabled = false;
    config.audioOutputReactive = false;
    config.commentaryStreamingEnabled = false;
    config.screenCommentaryAutoEnabled = false;
    config.scriptedEntranceEnabled = false;

    SettingsDialog dialog(config);

    auto *cameraEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("cameraEnabledCheckBox"));
    auto *cameraConsentGrantedCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("cameraConsentGrantedCheckBox"));
    auto *offlineModeCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("offlineModeCheckBox"));
    auto *cameraIndexSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("cameraIndexSpinBox"));
    auto *cameraTargetFpsSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("cameraTargetFpsSpinBox"));
    auto *eyeTrackingEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("eyeTrackingEnabledCheckBox"));
    auto *periodicScanEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("periodicScanEnabledCheckBox"));
    auto *periodicScanIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("periodicScanIntervalSpinBox"));
    auto *reactiveCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("audioOutputReactiveCheckBox"));
    auto *pollSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("audioOutputPollIntervalSpinBox"));
    auto *microphoneEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("microphoneEnabledCheckBox"));
    auto *voiceInputModeComboBox = dialog.findChild<QComboBox *>(QStringLiteral("voiceInputModeComboBox"));
    auto *wakeupEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("wakeupEnabledCheckBox"));
    auto *wakeupPhrasesEdit = dialog.findChild<QLineEdit *>(QStringLiteral("wakeupPhrasesEdit"));
    auto *wakeupLanguageEdit = dialog.findChild<QLineEdit *>(QStringLiteral("wakeupLanguageEdit"));
    auto *asrProviderComboBox = dialog.findChild<QComboBox *>(QStringLiteral("asrProviderComboBox"));
    auto *providerComboBox = dialog.findChild<QComboBox *>(QStringLiteral("providerComboBox"));
    auto *testApiButton = dialog.findChild<QPushButton *>(QStringLiteral("testApiButton"));
    auto *autoCommentaryCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("screenCommentaryAutoEnabledCheckBox"));
    auto *autoCommentaryIntervalSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("screenCommentaryAutoIntervalSpinBox"));
    auto *streamingCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("commentaryStreamingEnabledCheckBox"));
    auto *streamChunkSpinBox = dialog.findChild<QSpinBox *>(QStringLiteral("commentaryStreamChunkCharsSpinBox"));
    auto *scriptedEnabledCheckBox = dialog.findChild<QCheckBox *>(QStringLiteral("scriptedEntranceEnabledCheckBox"));
    auto *trajectoryEdit = dialog.findChild<QLineEdit *>(QStringLiteral("scriptedTrajectoryPathEdit"));

    QVERIFY(cameraEnabledCheckBox != nullptr);
    QVERIFY(cameraConsentGrantedCheckBox != nullptr);
    QVERIFY(offlineModeCheckBox != nullptr);
    QVERIFY(cameraIndexSpinBox != nullptr);
    QVERIFY(cameraTargetFpsSpinBox != nullptr);
    QVERIFY(eyeTrackingEnabledCheckBox != nullptr);
    QVERIFY(periodicScanEnabledCheckBox != nullptr);
    QVERIFY(periodicScanIntervalSpinBox != nullptr);
    QVERIFY(reactiveCheckBox != nullptr);
    QVERIFY(pollSpinBox != nullptr);
    QVERIFY(microphoneEnabledCheckBox != nullptr);
    QVERIFY(voiceInputModeComboBox != nullptr);
    QVERIFY(wakeupEnabledCheckBox != nullptr);
    QVERIFY(wakeupPhrasesEdit != nullptr);
    QVERIFY(wakeupLanguageEdit != nullptr);
    QVERIFY(asrProviderComboBox != nullptr);
    QVERIFY(providerComboBox != nullptr);
    QVERIFY(testApiButton != nullptr);
    QVERIFY(autoCommentaryCheckBox != nullptr);
    QVERIFY(autoCommentaryIntervalSpinBox != nullptr);
    QVERIFY(streamingCheckBox != nullptr);
    QVERIFY(streamChunkSpinBox != nullptr);
    QVERIFY(scriptedEnabledCheckBox != nullptr);
    QVERIFY(trajectoryEdit != nullptr);

    QCOMPARE(cameraIndexSpinBox->isEnabled(), false);
    QCOMPARE(cameraTargetFpsSpinBox->isEnabled(), false);
    QCOMPARE(eyeTrackingEnabledCheckBox->isEnabled(), false);
    QCOMPARE(periodicScanEnabledCheckBox->isEnabled(), false);
    QCOMPARE(periodicScanIntervalSpinBox->isEnabled(), false);
    QCOMPARE(pollSpinBox->isEnabled(), false);
    QCOMPARE(voiceInputModeComboBox->isEnabled(), false);
    QCOMPARE(wakeupEnabledCheckBox->isEnabled(), false);
    QCOMPARE(wakeupPhrasesEdit->isEnabled(), false);
    QCOMPARE(wakeupLanguageEdit->isEnabled(), false);
    QCOMPARE(asrProviderComboBox->isEnabled(), false);
    QCOMPARE(autoCommentaryIntervalSpinBox->isEnabled(), false);
    QCOMPARE(streamChunkSpinBox->isEnabled(), false);
    QCOMPARE(trajectoryEdit->isEnabled(), false);

    cameraEnabledCheckBox->setChecked(true);
    QCOMPARE(cameraIndexSpinBox->isEnabled(), false);

    cameraConsentGrantedCheckBox->setChecked(true);
    QCOMPARE(cameraIndexSpinBox->isEnabled(), true);
    QCOMPARE(cameraTargetFpsSpinBox->isEnabled(), true);
    QCOMPARE(eyeTrackingEnabledCheckBox->isEnabled(), true);
    QCOMPARE(periodicScanEnabledCheckBox->isEnabled(), true);
    QCOMPARE(periodicScanIntervalSpinBox->isEnabled(), true);

    periodicScanEnabledCheckBox->setChecked(false);
    QCOMPARE(periodicScanIntervalSpinBox->isEnabled(), false);

    reactiveCheckBox->setChecked(true);
    QCOMPARE(pollSpinBox->isEnabled(), true);

    microphoneEnabledCheckBox->setChecked(true);
    QCOMPARE(voiceInputModeComboBox->isEnabled(), true);
    QCOMPARE(asrProviderComboBox->isEnabled(), true);
    QCOMPARE(wakeupEnabledCheckBox->isEnabled(), false);

    voiceInputModeComboBox->setCurrentIndex(qMax(0, voiceInputModeComboBox->findData(QStringLiteral("continuous"))));
    QCOMPARE(wakeupEnabledCheckBox->isEnabled(), true);

    wakeupEnabledCheckBox->setChecked(true);
    QCOMPARE(wakeupPhrasesEdit->isEnabled(), true);
    QCOMPARE(wakeupLanguageEdit->isEnabled(), true);

    autoCommentaryCheckBox->setChecked(true);
    QCOMPARE(autoCommentaryIntervalSpinBox->isEnabled(), true);

    streamingCheckBox->setChecked(true);
    QCOMPARE(streamChunkSpinBox->isEnabled(), true);

    scriptedEnabledCheckBox->setChecked(true);
    QCOMPARE(trajectoryEdit->isEnabled(), true);

    offlineModeCheckBox->setChecked(true);
    QCOMPARE(providerComboBox->isEnabled(), false);
    QCOMPARE(testApiButton->isEnabled(), false);
    QCOMPARE(asrProviderComboBox->isEnabled(), false);
    QCOMPARE(autoCommentaryCheckBox->isEnabled(), false);
    QCOMPARE(streamingCheckBox->isEnabled(), false);
}

void SettingsDialogTest::endpointPresetAppliesProviderDefaults()
{
    SettingsDialog dialog(AppConfig{});

    auto *endpointPresetComboBox = dialog.findChild<QComboBox *>(QStringLiteral("endpointPresetComboBox"));
    auto *providerComboBox = dialog.findChild<QComboBox *>(QStringLiteral("providerComboBox"));
    auto *modelEdit = dialog.findChild<QLineEdit *>(QStringLiteral("modelEdit"));
    auto *baseUrlEdit = dialog.findChild<QLineEdit *>(QStringLiteral("baseUrlEdit"));

    QVERIFY(endpointPresetComboBox != nullptr);
    QVERIFY(providerComboBox != nullptr);
    QVERIFY(modelEdit != nullptr);
    QVERIFY(baseUrlEdit != nullptr);

    endpointPresetComboBox->setCurrentIndex(qMax(0, endpointPresetComboBox->findText(QStringLiteral("DeepSeek 官方"))));

    QCOMPARE(providerComboBox->currentText(), QStringLiteral("deepseek"));
    QCOMPARE(modelEdit->text(), QStringLiteral("deepseek-chat"));
    QCOMPARE(baseUrlEdit->text(), QStringLiteral("https://api.deepseek.com/v1"));
}

QTEST_MAIN(SettingsDialogTest)

#include "test_settings_dialog.moc"
